config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]

  root to: 'home#index'

  resources :categories, only: %i[new create index] do
    resources :transactions, only: %i[index create new]
  end

  resources :users, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :operations, through: :money_groups

  validates :name, presence: true, length: { minimum: 3 }
  validates :icon, presence: true

  def ordered_transactions
    operations.order(created_at: :desc)
  end
end

app/models/money_group.rb
class MoneyGroup < ApplicationRecord
  belongs_to :group
  belongs_to :operation

  after_create :increment_amount
  before_destroy :decrement_amount

  private

  def increment_amount
    current_amount = group.total_amount
    group.update(total_amount: current_amount + operation.amount)
  end

  def decrement_amount
    subtracted_amount = group.total_amount - operation.amount
    group.update(total_amount: subtracted_amount)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :groups, through: :money_groups

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy, foreign_key: 'user_id'
  has_many :operations, dependent: :destroy, foreign_key: 'user_id'

  validates :name, presence: true

  def ordered_groups
    groups.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end

  # # Catch all CanCan errors and alert the user of the exception
  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :splash

  def index
    @categories = current_user.ordered_groups
  end

  def new
    @category = current_user
    group = Group.new
    respond_to do |format|
      format.html { render :new, locals: { group: group } }
    end
  end

  def create
    category = Group.new(category_params)
    category.user = current_user
    respond_to do |format|
      format.html do
        if category.save
          flash[:notice] = 'Category was successfully created.'
          redirect_to categories_path
        else
          flash[:alert] = 'Category was not created.'
          render :new, locals: { group: category }
        end
      end
    end
  end

  private

  def category_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @group = current_user.groups.find(params[:category_id])
    @transactions = @group.ordered_transactions
  end

  def new
    @categories = current_user.ordered_groups
    operation = Operation.new
    id = params[:category_id]
    respond_to do |format|
      format.html { render :new, locals: { operation: operation, id: id } }
    end
  end

  def create
    name = transaction_params[:name]
    amount = transaction_params[:amount]
    categories = transaction_params[:categories]
    transaction = Operation.new(name: name, amount: amount)
    transaction.user = current_user
    respond_to do |format|
      format.html do
        if transaction.save
          create_relation(categories, transaction, params[:id])
        else
          @categories = current_user.groups
          flash.now[:alert] = 'Error: Please make sure to fill all fields with the proper input'
          render :new, status: 422, locals: { operation: transaction, id: params[:category_id] }
        end
      end
    end
  end

  private

  def transaction_params
    params.require(:operation).permit(:name, :amount, categories: [])
  end

  def create_relation(categories, transaction, id)
    # First record is empty so gets deleted
    categories.shift

    # If no category was selected
    if categories.empty?
      @categories = current_user.groups
      flash.now[:alert] = 'Error: Please make sure to fill all fields with the proper input'
      render :new, status: 422, locals: { operation: transaction, id: id }
      return
    end

    first_category_id = categories[0]

    # Iterates through the categories and create relationships with the operation
    categories.each_with_index do |category_id, _index|
      group = Group.find(category_id)
      MoneyGroup.create(group: group, operation: transaction)
    end
    flash[:notice] = 'Transaction created successfully'
    redirect_to(category_transactions_path(category_id: first_category_id))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    redirect_to new_user_registration_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= render 'common/navigation', :title => 'Categories' %>
<section class="container flex">
  <ul class="list flex">
    <% @categories.each do |category| %>
      <li class="item flex">
        <img src=<%= category.icon %> alt=<%= category.name %> >

        <div class="item-details flex">
          <%= link_to category_transactions_path(category_id: category.id), id: "Group-#{category.id}" do %>
            <h3> <%= category.name %> </h3>
          <% end %>
          <p> $<%= category.total_amount %> </p>
        </div>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Add New Category', new_category_path,  class: "btn" %>
</section>

app/views/categories/new.html.erb
<%= render 'common/navigation', :title => 'Categories' %>
<section class="access flex">
  <%= form_with model: group, url: categories_url, method: :post do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, placeholder: 'Name (Minimun 3 characters)' %>
    </div>

    <div class="field">
      <%= f.label :icon %>
      <%= f.text_field :icon, autofocus: true, placeholder: 'Icon (Please add a proper URL)' %>
    </div>

    <div class="actions mt-5">
      <%= f.submit "Save", class: "submit" %>
    </div>
  <% end %>
</section>

app/views/common/_navigation.html.erb
<header class="header flex">
  <%= link_to '/', id: 'Home' do %>
    <span class="header-action">
      Back
    </span>
  <% end %>
  <h2><%= title %></h2>
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <span class="header-action">
        logout
      </span>
    <% end %>
  <% end %>
</header>

app/views/home/index.html.erb
<section class="greeting container flex">
  <div class="text flex">
  <h1> Cash<span>App</span> </h1>
  <p> Track your spending and save money </p>
  </div>
  <div class="content flex">
    <% if user_signed_in?  %>
    <span class="link">
      <%= link_to 'Categories', categories_path, class: "btn" %>
    </span>
    <% else %>
    <div class="btn-group flex">
      <%= link_to 'Log in', new_user_session_path, class: "btn" %>
      <%= link_to 'Sign up', new_user_registration_path, class: "btn" %>
    </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<%= render 'common/navigation', :title => 'Transactions' %>
<section class="container flex">
  <div class="sum flex">
      <h3>Total amount:</h3>
      <span class="amount">$<%= @group.total_amount %></span>
  </div>
  <ul class="transactions flex">
    <% @transactions.each do |transaction| %>
      <li>
        <h2> <%= transaction.name %> </h2>
        <p> $<%= transaction.amount %> </p>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Add a new transaction', new_category_transaction_path(category_id: @group.id),  class: "btn" %>
</section>

app/views/transactions/new.html.erb
<%= render 'common/navigation', :title => 'Transaction' %>
<section class="access flex">
  <%= form_with model: operation, url: category_transactions_url(category_id: id), method: :post do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, placeholder: 'Name (Minimun 3 characters)' %>
    </div>

    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount, autofocus: true, placeholder: 'Amount (Greater than 0)' %>
    </div>

    <div class="field">
      <%= f.label :categories%>
      <%= f.select :categories, @categories.map { |t| [t.name, t.id]}, { :selected => id }, { :multiple => true, class: "categories"} %>
    </div>

    <div>
      <%= f.submit "Save", class: "submit" %>
    </div>
  <% end %>
</section>